# Generated by Django 2.2 on 2020-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_correlativo', models.IntegerField()),
                ('eje_estrategico', models.CharField(max_length=100)),
                ('requerimiento', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_solped', models.DateField()),
                ('nombre', models.CharField(max_length=75)),
                ('descripcion', models.TextField(max_length=240)),
                ('objetivo', models.TextField(max_length=300)),
                ('beneficio', models.TextField(max_length=500)),
                ('impacto', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('sponsor', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=100)),
                ('capa_red', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
