# Generated by Django 2.2 on 2020-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='beneficio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='capa_red',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='descripcion',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='eje_estrategico',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fecha_solicitud',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fecha_solped',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='impacto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='nombre',
            field=models.CharField(default='Nombre de la iniciativa', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='nro_correlativo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='objetivo',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='requerimiento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='solicitante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='sponsor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='ubicacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
