# Generated by Django 2.2 on 2020-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativa', '0002_auto_20200811_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='beneficio',
            field=models.TextField(default='Optimizar los procesos...', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='capa_red',
            field=models.CharField(default='TRANSPORTE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='descripcion',
            field=models.TextField(default='Esta iniciativa consiste en...', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fin',
            field=models.DateField(default='2020-09-30', null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='impacto',
            field=models.CharField(default='Retraso en las operaciones del area logistica', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='inicio',
            field=models.DateField(default='2020-09-01', null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='nombre',
            field=models.CharField(default='Iniciativa 1', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='objetivo',
            field=models.TextField(default='El objetivo es...', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='solicitante',
            field=models.CharField(default='JEFATURA DE PROCESOS INTERNOS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='sponsor',
            field=models.CharField(default='GERENCIA DE OPERACIONES', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='tipo',
            field=models.CharField(default='Reingenieria', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='ubicacion',
            field=models.CharField(default='Perú', max_length=100, null=True),
        ),
    ]
