# Generated by Django 2.2 on 2020-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativa', '0003_auto_20200811_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='eje_estrategico',
            field=models.CharField(default='Capacidad_I_Calidad_de_Servicio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fecha_solicitud',
            field=models.DateField(default='2020-08-11', null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='fecha_solped',
            field=models.DateField(default='2020-08-11', null=True),
        ),
        migrations.AlterField(
            model_name='iniciativa',
            name='requerimiento',
            field=models.CharField(default='Incrementar %X en Capacidad de Transporte', max_length=100, null=True),
        ),
    ]
